version: "3"
services:
  app:
    container_name: etl
    image: etl:latest
    tty: true
    volumes:
      - ./etl:/etl
    env_file:
      - ./etl.env
  postgres:
    container_name: postgres
    image: postgres:latest
    env_file:
      - ./etl.env
    ports:
    - "5432:5432"
